apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: default
  labels:
    app: paymybuddy
type: Opaque
stringData:
  # Credentials extraites du Dockerfile officiel PayMyBuddy eazytraining
  mysql-root-password: "password"
  mysql-username: "root"
  mysql-password: "password"
  mysql-database: "db_paymybuddy"
