apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: default
  labels:
    app: paymybuddy
type: Opaque
stringData:
  mysql-root-password: "rootpassword"
  mysql-user: "pmb_user"
  mysql-password: "pmb_password"
  mysql-database: "paymybuddy"
